

*****************************************************************************
QEPPlib has basinc functionalities that depends only on standard C libraries.
External libraries are used to provide further capabilities
If this libraries are not included, some functions will be disabled

   mpi:      
   xml2:      -I/usr/include/libxml2 -D__LIBXML2     -lxml2"
   gsl:          


  CC:        gcc
  CPPFLAGS:  -I/usr/include/libxml2 -D__LIBXML2 -I./inc -I/home/crivella/.local/inc
  LDFLAGS:   
  LIBS:      -lxml2

*****************************************************************************

